name: EquestriCraftPlugin
main: io.github.davidg95.equestricraftplugin.EquestriCraftPlugin
version: 1.0
commands:
    equestristatus:
       description: Shows a status update.
       usage: /<command>
    createhorse:
        description: Creates a new horse.
        usage: /createhorse <stallion|mare|gelding>
    geldingtool:
        description: Place a gelding tool in your hand.
        usage: /geldingtool
    horsemedicine:
        description: Place healing medicine in your hand.
        usage: /horsemedicine
    horsewand:
        description: Place checking wand in your hand.
        usage: /horsecheck
    vaccination:
        description: Spawns the vaccination tool.
        usage: /vaccination
    doctor:
        description: doctor commands.
        usage: /doctor <add|remove|reset|list> [playername]
    doctortool:
        description: Spawn the tool to check a horses health.
        usage: /doctortool
    changegender:
        description: Change the gender of a horse.
        usage: /changegender <stallion|mare|gelding> (must be on a horse)
    savehorses:
        description: Saves the horses to file.
        usage: /savehorses
    setbreed:
        description: Set the breed of a horse.
        usage: /setbreed <breed> (must be on a horse)
    setpersonality:
        description: Set the personality of a horse.
        usage: /setpersonality <personality> (must be on a horse)
    showbreeds:
        description: Show a list of the breeds.
        usage: /showbreeds
    showtraits:
        description: Show a list of the traits/personalities.
        usage: /showtraits
    eqhelp:
        decription: Show a list of help commands.
        usage: /eqhelp
    setage:
        description: Set the age of the horse.
        usage: /setage <age> (must be on a horse
    race:
        description: Race commands.
        usage: /race <options>
    eqh:
        decription: general command
        usage: /eqh
    farrier:
        description: farrier commands.
        usage: /farrier <add|remove|list|reset|tool> [playername].
    disciplines:
        description: disciplines commands.
        usage: /disciplines
    setlevel:
        description: sets a horses training level.
        udage: /setlevel <1-10>
    navigator:
        description: Spawns the navigator.
        udage: /navigator
    auction:
        description: Auction commands.
        usage: /auction [open|bid|sell]
    breeding:
        description: breeding commands.
        usage: /breeding [gapple|check]
    food:
        description: food commands.
        usage: /food [buy-seeds|buy-wheat|buy-water]