name: EquestriCraftPlugin
main: io.github.davidg95.equestricraftplugin.EquestriCraftPlugin
version: 1.0
commands:
    equestristatus:
       description: Shows a status update.
       usage: /<command>
    createhorse:
        description: Creates a new horse.
        usage: /createhorse <stallion|mare|gelding>
    geldingtool:
        description: Place a gelding tool in your hand.
        usage: /geldingtool
    horsemedicine:
        description: Place healing medicine in your hand.
        usage: /horsemedicine
    horsewand:
        description: Place checking wand in your hand.
        usage: /horsecheck
    vaccination:
        description: Spawns the vaccination tool.
        usage: /vaccination
    adddoctor:
        description: Make a player a doctor.
        usage: /adddoctor <playername>
    changegender:
        description: Change the gender of a horse.
        usage: /changegender <stallion|mare|gelding>
    savehorses:
        description: Saves the horses to file.
        usage: /savehorses