name: EquestriCraftPlugin
main: io.github.davidg95.equestricraftplugin.EquestriCraftPlugin
version: 1.0
commands:
    equestristatus:
       description: Shows a status update.
       usage: /<command>
       permission: EquestriCraftPlugin.equestristatus
       permission-message: You don't have <permission>
    createhorse:
        description: Creates a new horse.
        usage: /createhorse <stallion|mare|gelding>
        permission: EquestriCraftPlugin.createhorse
        permission-message: You don't have <permission>
    geldingtool:
        description: Place a gelding tool in your hand.
        usage: /geldingtool
        permission: EquestriCraftPlugin.geldingtool
        permission-message: You don't have <permission>
    horsemedicine:
        description: Place healing medicine in your hand.
        usage: /horsemedicine
        permission: EquestriCraftPlugin.horcemedicine
        permission-message: You dont have <permission>